ERROR:project:Exception on /chats [GET]
Traceback (most recent call last):
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/CryptoAlert/project/main.py", line 128, in chatssss
    for item in Chat.query.all():
NameError: name 'Chat' is not defined
ERROR:project:Exception on /chats [GET]
Traceback (most recent call last):
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/CryptoAlert/project/main.py", line 128, in chatssss
    for item in Chat.query.all():
NameError: name 'Chat' is not defined
ERROR:project:Exception on /chats [GET]
Traceback (most recent call last):
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/CryptoAlert/project/main.py", line 128, in chatssss
    for item in Chat.query.all():
NameError: name 'Chat' is not defined
ERROR:project:Exception on /chat [GET]
Traceback (most recent call last):
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/CryptoAlert/project/chat.py", line 19, in sessions
    chat = Chat.query.filter_by(user = current_user.id)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
ERROR:project:Exception on /chat [GET]
Traceback (most recent call last):
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/CryptoAlert/ars/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/CryptoAlert/project/chat.py", line 19, in sessions
    chat = Chat.query.filter_by(user = current_user.id)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
